name: Build and Publish

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Clean project
        run: ./mvnw clean

      - name: Compile only
        run: ./mvnw compile

      # - name: Run tests 
      #   run: ./mvnw test

      - name: Package (without rerunning tests)
        run: ./mvnw package -DskipTests
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: target/*.jar
  
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact  # Matches the uploaded name
          

      - name: Verify artifact
        run: |
          ls -la