name: Publish to Artifactory

on:
  workflow_run:
    workflows: ["Build, Test and Package"]
    types:
      - completed
permissions:
  id-token: write

jobs:
  upload:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
            name: app-artifact
            path: target/

      - name: Set  Artifactory
        uses: jfrog/setup-jfrog-cli@v4
        env:
            JF_URL: https://trial3sr477.jfrog.io
        with:
            oidc-provider-name: github-jfrog
            oidc-audience: my-aud
        
      - name: Publish to Artifactory
        run: jf rt upload --url="$JF_URL" "target/*.jar" "libs-snapshot-local/"
      
    #   - name: Checkout code
    #     uses: actions/checkout@v4

    #   - name: Set up JDK
    #     uses: actions/setup-java@v4
    #     with:
    #       distribution: 'temurin'
    #       java-version: '17'

    #   - name: Restore build 
    #     run: ./mvnw clean package -DskipTests

    #   - name: publish to Artifactory
    #     uses: jfrog/setup-jfrog-cli@v4
    #     env:
    #         JF_URL: https://trial3sr477.jfrog.io 
    #     with:
    #         oidc-provider-name: github-jfrog 
    #         oidc-audience: my-aud


        